import 'package:flutter/material.dart';
import 'package:weather_icons/weather_icons.dart';

class IconConverter {
  static final Map<String, IconData> dayIconsDict = {
    '200': WeatherIcons.thunderstorm,
    '201': WeatherIcons.thunderstorm,
    '202': WeatherIcons.thunderstorm,
    '210': WeatherIcons.thunderstorm,
    '211': WeatherIcons.thunderstorm,
    '212': WeatherIcons.thunderstorm,
    '221': WeatherIcons.thunderstorm,
    '230': WeatherIcons.thunderstorm,
    '231': WeatherIcons.thunderstorm,
    '232': WeatherIcons.thunderstorm,
    '300': WeatherIcons.day_sleet,
    '301': WeatherIcons.day_sleet,
    '302': WeatherIcons.day_sleet,
    '310': WeatherIcons.day_sleet,
    '311': WeatherIcons.day_sleet,
    '312': WeatherIcons.day_sleet,
    '313': WeatherIcons.day_sleet,
    '314': WeatherIcons.day_sleet,
    '321': WeatherIcons.day_sleet,
    '500': WeatherIcons.day_showers,
    '501': WeatherIcons.day_showers,
    '502': WeatherIcons.day_showers,
    '503': WeatherIcons.day_showers,
    '504': WeatherIcons.day_showers,
    '511': WeatherIcons.day_snow_wind,
    '520': WeatherIcons.day_rain,
    '521': WeatherIcons.day_rain,
    '522': WeatherIcons.day_rain,
    '531': WeatherIcons.day_rain,
    '600': WeatherIcons.day_snow_wind,
    '601': WeatherIcons.day_snow_wind,
    '602': WeatherIcons.day_snow_wind,
    '611': WeatherIcons.day_snow_wind,
    '612': WeatherIcons.day_snow_wind,
    '613': WeatherIcons.day_snow_wind,
    '615': WeatherIcons.day_snow_wind,
    '616': WeatherIcons.day_snow_wind,
    '620': WeatherIcons.day_snow_wind,
    '621': WeatherIcons.day_snow_wind,
    '622': WeatherIcons.day_snow_wind,
    '701': WeatherIcons.day_fog,
    '711': WeatherIcons.day_fog,
    '721': WeatherIcons.day_fog,
    '731': WeatherIcons.day_fog,
    '741': WeatherIcons.day_fog,
    '751': WeatherIcons.day_fog,
    '761': WeatherIcons.day_fog,
    '762': WeatherIcons.day_fog,
    '771': WeatherIcons.day_fog,
    '781': WeatherIcons.day_fog,
    '800': WeatherIcons.day_sunny,
    '801': WeatherIcons.day_cloudy,
    '802': WeatherIcons.day_cloudy,
    '803': WeatherIcons.day_cloudy,
    '804': WeatherIcons.day_cloudy,
  };

  static final Map<String, IconData> nightIconsDict = {
    '200': WeatherIcons.thunderstorm,
    '201': WeatherIcons.thunderstorm,
    '202': WeatherIcons.thunderstorm,
    '210': WeatherIcons.thunderstorm,
    '211': WeatherIcons.thunderstorm,
    '212': WeatherIcons.thunderstorm,
    '221': WeatherIcons.thunderstorm,
    '230': WeatherIcons.thunderstorm,
    '231': WeatherIcons.thunderstorm,
    '232': WeatherIcons.thunderstorm,
    '300': WeatherIcons.night_sleet,
    '301': WeatherIcons.night_sleet,
    '302': WeatherIcons.night_sleet,
    '310': WeatherIcons.night_sleet,
    '311': WeatherIcons.night_sleet,
    '312': WeatherIcons.night_sleet,
    '313': WeatherIcons.night_sleet,
    '314': WeatherIcons.night_sleet,
    '321': WeatherIcons.night_sleet,
    '500': WeatherIcons.night_showers,
    '501': WeatherIcons.night_showers,
    '502': WeatherIcons.night_showers,
    '503': WeatherIcons.night_showers,
    '504': WeatherIcons.night_showers,
    '511': WeatherIcons.night_snow_wind,
    '520': WeatherIcons.night_rain,
    '521': WeatherIcons.night_rain,
    '522': WeatherIcons.night_rain,
    '531': WeatherIcons.night_rain,
    '600': WeatherIcons.night_snow_wind,
    '601': WeatherIcons.night_snow_wind,
    '602': WeatherIcons.night_snow_wind,
    '611': WeatherIcons.night_snow_wind,
    '612': WeatherIcons.night_snow_wind,
    '613': WeatherIcons.night_snow_wind,
    '615': WeatherIcons.night_snow_wind,
    '616': WeatherIcons.night_snow_wind,
    '620': WeatherIcons.night_snow_wind,
    '621': WeatherIcons.night_snow_wind,
    '622': WeatherIcons.night_snow_wind,
    '701': WeatherIcons.night_fog,
    '711': WeatherIcons.night_fog,
    '721': WeatherIcons.night_fog,
    '731': WeatherIcons.night_fog,
    '741': WeatherIcons.night_fog,
    '751': WeatherIcons.night_fog,
    '761': WeatherIcons.night_fog,
    '762': WeatherIcons.night_fog,
    '771': WeatherIcons.night_fog,
    '781': WeatherIcons.night_fog,
    '800': WeatherIcons.night_clear,
    '801': WeatherIcons.night_cloudy,
    '802': WeatherIcons.night_cloudy,
    '803': WeatherIcons.night_cloudy,
    '804': WeatherIcons.night_cloudy,
  };
}

extension ApiResponseIconConverting on String {
  IconData getWeatherIcon(int sunrise, int sunset){
      var curTimestamp = DateTime.now().toUtc().millisecondsSinceEpoch;

      // TODO: Add error logging if response code isn't found in dictionary

      if (curTimestamp > sunrise && curTimestamp < sunset){
        return IconConverter.dayIconsDict[this];
      }

      else return IconConverter.nightIconsDict[this];
  }
}